### ISSUE TITLE
submitting feedback to something like metacran?

### ISSUE THREAD

**Issue by sckott** [noamross/htmlhelp#1]
You mentioned you can't submit feedback (no http requests) - maybe just link to the appropriate page on metacran, eg.,  http://www.r-pkg.org/pkg/ggplot2  

of course requires metacran to have option to gather feedback. 

@gaborcsardi

**Comment by noamross** [comment]
Yeah, in general one can just send someone to metacran or github via a link.  That doesn't require HTML in the help file.

It seems one can get images and other resources from external sources (e.g., https://github.com/noamross/htmlhelp/blob/master/R/hello.R#L14), so there are http requests.  iframes with external resources don't seem to work, though, which is what google form embeds require.

Know any easy-to-use service that I can send data to via a form's `action` field to test if it works?

**Comment by sckott** [comment]
ah, okay, just not iframes, makes sense. 

maybe http://httpbin.org/ and http://httpbin.org/forms/post

**Comment by gaborcsardi** [comment]
How about just having a like button, or something simple that can go to metacran and metacran can redirect it back to the original page?

Although that's not very good for more detailed feedback. But you can embed a form as well, I guess. You could generate the form from an R command, so that it does not have to be added by hand. Or generate it with a custom roxygen tag.

**Comment by noamross** [comment]
@gaborcsardi Is there documentation somewhere on how to create custom tags? I haven't found any. Or do you mean templates?

**Comment by gaborcsardi** [comment]
@noamross: right, for proper tags you would need to modify roxygen. But you can define a custom parsers for the existing tags, and put in the form there.

But I am not sure if this is a good idea, actually, because you need to use a custom package instead of roxygen. 

You can also have user-defined Rd commands, maybe that makes more sense.
